<a href="https://colab.research.google.com/github/BikramKC7/PyTorch/blob/main/Dataset_%26_DataLoader_Class_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 from sklearn.datasets import make_classification
 import torch
 import pandas as pd

In [2]:
# Step 1 : Create a synthetic classification dataset using sklearn

X,y = make_classification(
    n_samples = 10,      #number of samples data
    n_features = 2,       # no. of features , X
    n_informative=2,      # number of informative features
    n_redundant=0,        # number of redundant features
    n_classes=2,          # number of classes in Y
    random_state=42      # for reproducibility
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
X.shape

(10, 2)

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
y.shape

(10,)

In [7]:
#Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [8]:
from torch.utils.data import Dataset,DataLoader

In [9]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [10]:
dataset = CustomDataset(X,y)

In [12]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [13]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-0.5872, -1.9717],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-1.9629, -0.9923]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
